// One-shot dev tool: converts a directory of claudepix pixel-art JSON files
// into src/animations.ts. The output is committed, so you only need this when
// regenerating the artwork.
//
//   node tools/convert_animations.mjs <path-to-claudepix-json-dir>
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const SRC = process.argv[2];
if (!SRC) {
  console.error("usage: node tools/convert_animations.mjs <path-to-claudepix-json-dir>");
  process.exit(1);
}
const OUT = join(dirname(fileURLToPath(import.meta.url)), "..", "src", "animations.ts");

const anims = [];
for (const file of readdirSync(SRC).filter((f) => f.endsWith(".json") && !f.startsWith("_")).sort()) {
  const j = JSON.parse(readFileSync(join(SRC, file), "utf8"));
  anims.push({
    name: j.name,
    palette: j.palette,
    // Flatten each 20x20 grid of palette indices (0-9) into a 400-char string.
    frames: j.frames.map((fr) => ({ hold: fr.hold, grid: fr.grid.flat().join("") })),
  });
}

const out =
  `// GENERATED by tools/convert_animations.mjs — do not edit.\n` +
  `// Source: Clawdmeter claudepix_data (pixel art from claudepix.vercel.app).\n` +
  `export interface ClawdFrame {\n  hold: number;\n  /** 400 chars, row-major 20x20 palette indices */\n  grid: string;\n}\n\n` +
  `export interface ClawdAnimation {\n  name: string;\n  /** CSS colors; "transparent" = skip pixel */\n  palette: string[];\n  frames: ClawdFrame[];\n}\n\n` +
  `export const ANIMATIONS: Record<string, ClawdAnimation> = ${JSON.stringify(
    Object.fromEntries(anims.map((a) => [a.name, a])),
  )};\n`;

writeFileSync(OUT, out);
console.log(`wrote ${OUT} (${anims.length} animations: ${anims.map((a) => a.name).join(", ")})`);
