// One-shot dev tool: converts a pixel-anim mascot's animation files into
// src/<mascot>.ts, matching the palette-indexed shape of src/animations.ts.
// The output is committed, so you only need this when regenerating the artwork.
//
//   PIXEL_ANIM_DIR=<pixel-anim/animations> node tools/convert_mascot.mjs <mascot>
//   node tools/convert_mascot.mjs <mascot> <pixel-anim/animations>  # arg overrides env
//
// <mascot> selects the per-character subdir (e.g. "axolotl", "cat"). The source
// root lives outside this repo, so it's read from the environment (or a CLI
// override) rather than hard-coded.
//
// Two source formats are supported (see animations/creature-engine.js):
//   - engine presets: `window.PRESET = { frames: [{ hold, frame|null }] }` drawn
//     over a per-mount base; we capture the mount opts (base/color/stripeColor).
//   - standalone files: `window.FRAMES` + `window.PAL` (a full CSS palette).
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import vm from "node:vm";

const MASCOT = process.argv[2];
const ROOT = process.argv[3] ?? process.env.PIXEL_ANIM_DIR;
if (!MASCOT || !ROOT) {
  console.error(
    "usage: PIXEL_ANIM_DIR=<pixel-anim/animations> node tools/convert_mascot.mjs <mascot>",
  );
  process.exit(1);
}
const SRC = join(ROOT, MASCOT);
const OUT = join(dirname(fileURLToPath(import.meta.url)), "..", "src", `${MASCOT}.ts`);
const CONST = `${MASCOT.toUpperCase()}_ANIMATIONS`;
const EYE = "#0f0f0f"; // palette value 2, fixed in creature-engine.js

// The shared engine sits in the mascot dir or one level up (per-mascot subdirs).
const enginePath = [join(SRC, "creature-engine.js"), join(ROOT, "creature-engine.js")].find(
  existsSync,
);
if (!enginePath) {
  console.error(`creature-engine.js not found in ${SRC} or ${ROOT}`);
  process.exit(1);
}
const engineSrc = readFileSync(enginePath, "utf8");

/** Run a file's inline <script> bodies in a DOM-stubbed sandbox and read it back.
 *  `mount` is replaced with a capturing stub so we get the base/color opts. */
function evalAnimation(html) {
  const stubEl = () => ({ style: {}, innerHTML: "", appendChild() {} });
  const sandbox = {
    document: { createElement: stubEl, getElementById: stubEl },
    performance: { now: () => 0 },
    requestAnimationFrame: () => 0,
    cancelAnimationFrame: () => {},
    addEventListener: () => {},
    postMessage: () => {},
  };
  sandbox.window = sandbox;
  const ctx = vm.createContext(sandbox);

  // The engine defines window.PixelEngine; standalone files ignore it.
  vm.runInContext(engineSrc, ctx);
  let mountOpts = null;
  sandbox.window.PixelEngine.mount = (_host, opts) => {
    mountOpts = opts;
    return {};
  };
  for (const body of inlineScripts(html)) vm.runInContext(body, ctx);

  return { win: sandbox.window, mountOpts };
}

/** Inline <script> bodies, in order, skipping `src="..."` includes. */
function inlineScripts(html) {
  return [...html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi)]
    .map((m) => m[1])
    .filter((body) => body.trim().length);
}

// One base36 char per cell (0-9a-z): keeps the 400-char grid while allowing
// palettes up to 36 colours. Decoded with parseInt(ch, 36) in splash.ts;
// digits 0-9 are identical to the old decimal encoding.
const flatten = (grid) => grid.map((row) => row.map((v) => v.toString(36)).join("")).join("");

const anims = {};
for (const file of readdirSync(SRC).filter((f) => f.endsWith(".html")).sort()) {
  const name = file.replace(/\.html$/, "").replace(/_/g, " ");
  const { win, mountOpts } = evalAnimation(readFileSync(join(SRC, file), "utf8"));

  let palette, frames;
  if (win.PRESET) {
    const { PixelEngine: eng } = win;
    const base = mountOpts?.base ?? eng.CREATURE;
    // Engine palette: 0 empty, 1 body, 2 eye, 3 stripe (see creature-engine.js).
    palette = ["transparent", mountOpts?.color ?? "#E8A0BF", EYE, mountOpts?.stripeColor ?? "#6E747A"];
    frames = win.PRESET.frames.map((fr) => ({ hold: fr.hold, grid: flatten(fr.frame ?? base) }));
  } else if (win.FRAMES && win.PAL) {
    if (win.PAL.length > 36) throw new Error(`${file}: palette >36 entries breaks single-char grid`);
    palette = win.PAL;
    frames = win.FRAMES.map((fr) => ({ hold: fr.hold, grid: flatten(fr.frame) }));
  } else {
    throw new Error(`${file}: no PRESET or FRAMES/PAL found`);
  }
  anims[name] = { name, palette, frames };
}

const out =
  `// GENERATED by tools/convert_mascot.mjs — do not edit.\n` +
  `// Source: pixel-anim ${MASCOT} mascot (PRESET / FRAMES animation files).\n` +
  `import type { ClawdAnimation } from "./animations";\n\n` +
  `export const ${CONST}: Record<string, ClawdAnimation> = ${JSON.stringify(anims)};\n`;

writeFileSync(OUT, out);
console.log(`wrote ${OUT} (${Object.keys(anims).length} animations: ${Object.keys(anims).join(", ")})`);
